import {
    LucideArrowLeft,
    LucideArrowRight,
    LucideBatteryFull,
    LucideBell,
    LucideBluetooth,
    LucideBookmark,
    LucideCalendar,
    LucideCamera,
    LucideCheck,
    LucideCheckCircle,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronUp,
    LucideCircleStop,
    LucideClock,
    LucideCloud,
    LucideEye,
    LucideEyeOff,
    LucideFile,
    LucideFlame,
    LucideFolder,
    LucideHeart,
    LucideHeartCrack,
    LucideHelpCircle,
    LucideHome,
    LucideImage,
    LucideInfo,
    LucideLink,
    LucideLock,
    LucideMail,
    LucideMap,
    LucideMapPin,
    LucideMic,
    LucideMinus,
    LucideMinusCircle,
    LucideMoon,
    LucideMoreHorizontal,
    LucidePause,
    LucidePencil,
    LucidePhone,
    LucidePlay,
    LucidePlus,
    LucideRefreshCw,
    LucideSearch,
    LucideSend,
    LucideSettings,
    LucideShare,
    LucideSquare,
    LucideStar,
    LucideSun,
    LucideTrash2,
    LucideTriangleAlert,
    LucideUmbrella,
    LucideUndo2,
    LucideUserCircle,
    LucideUsers,
    LucideWifi,
    LucideX,
    LucideZap,
} from "@lucide/angular";

export const LUCIDE_ICONS: Record<string, unknown> = {
    home: LucideHome,
    search: LucideSearch,
    settings: LucideSettings,
    bell: LucideBell,
    star: LucideStar,
    heart: LucideHeart,
    bookmark: LucideBookmark,
    share: LucideShare,
    "trash-2": LucideTrash2,
    pencil: LucidePencil,
    plus: LucidePlus,
    minus: LucideMinus,
    x: LucideX,
    "chevron-left": LucideChevronLeft,
    "chevron-right": LucideChevronRight,
    "chevron-up": LucideChevronUp,
    "chevron-down": LucideChevronDown,
    "more-horizontal": LucideMoreHorizontal,
    "refresh-cw": LucideRefreshCw,
    "undo-2": LucideUndo2,
    mail: LucideMail,
    "user-circle": LucideUserCircle,
    users: LucideUsers,
    check: LucideCheck,
    "check-circle": LucideCheckCircle,
    "triangle-alert": LucideTriangleAlert,
    info: LucideInfo,
    "help-circle": LucideHelpCircle,
    eye: LucideEye,
    "eye-off": LucideEyeOff,
    lock: LucideLock,
    calendar: LucideCalendar,
    clock: LucideClock,
    map: LucideMap,
    "map-pin": LucideMapPin,
    phone: LucidePhone,
    mic: LucideMic,
    camera: LucideCamera,
    image: LucideImage,
    play: LucidePlay,
    pause: LucidePause,
    square: LucideSquare,
    "stop-circle": LucideCircleStop,
    file: LucideFile,
    folder: LucideFolder,
    send: LucideSend,
    link: LucideLink,
    wifi: LucideWifi,
    bluetooth: LucideBluetooth,
    "battery-full": LucideBatteryFull,
    sun: LucideSun,
    moon: LucideMoon,
    cloud: LucideCloud,
    umbrella: LucideUmbrella,
    flame: LucideFlame,
    zap: LucideZap,
    "arrow-right": LucideArrowRight,
    "arrow-left": LucideArrowLeft,
    "minus-circle": LucideMinusCircle,
    "heart-crack": LucideHeartCrack,
};
