import {
    LucideArrowDown,
    LucideArrowLeft,
    LucideArrowRight,
    LucideArrowUp,
    LucideBatteryFull,
    LucideBell,
    LucideBluetooth,
    LucideBookmark,
    LucideCalendar,
    LucideCamera,
    LucideCheck,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronUp,
    LucideCircleCheckBig,
    LucideCircleMinus,
    LucideCircleQuestionMark,
    LucideCircleUser,
    LucideCircleX,
    LucideClock,
    LucideCloud,
    LucideEllipsis,
    LucideEye,
    LucideEyeOff,
    LucideFile,
    LucideFlame,
    LucideFolder,
    LucideHeart,
    LucideHeartCrack,
    LucideHouse,
    type LucideIcon,
    type LucideIconData,
    LucideImage,
    LucideInfo,
    LucideLink,
    LucideLock,
    LucideMail,
    LucideMap,
    LucideMapPin,
    LucideMenu,
    LucideMic,
    LucideMinus,
    LucideMoon,
    LucidePause,
    LucidePencil,
    LucidePhone,
    LucidePlay,
    LucidePlus,
    LucideRefreshCw,
    LucideSearch,
    LucideSend,
    LucideSettings,
    LucideShare,
    LucideSlidersHorizontal,
    LucideSparkles,
    LucideSquare,
    LucideSquarePen,
    LucideStar,
    LucideSun,
    LucideSunDim,
    LucideTrash2,
    LucideTriangleAlert,
    LucideUmbrella,
    LucideUndo2,
    LucideUsers,
    LucideVolume,
    LucideVolume1,
    LucideVolume2,
    LucideWifi,
    LucideX,
    LucideZap,
} from "@lucide/angular";

export const LUCIDE_ICONS = {
    home: LucideHouse,
    search: LucideSearch,
    settings: LucideSettings,
    bell: LucideBell,
    star: LucideStar,
    heart: LucideHeart,
    bookmark: LucideBookmark,
    share: LucideShare,
    "trash-2": LucideTrash2,
    pencil: LucidePencil,
    plus: LucidePlus,
    minus: LucideMinus,
    x: LucideX,
    "circle-x": LucideCircleX,
    "square-pen": LucideSquarePen,
    menu: LucideMenu,
    "sliders-horizontal": LucideSlidersHorizontal,
    "chevron-left": LucideChevronLeft,
    "chevron-right": LucideChevronRight,
    "chevron-up": LucideChevronUp,
    "chevron-down": LucideChevronDown,
    "more-horizontal": LucideEllipsis,
    "refresh-cw": LucideRefreshCw,
    "undo-2": LucideUndo2,
    mail: LucideMail,
    "user-circle": LucideCircleUser,
    users: LucideUsers,
    check: LucideCheck,
    "check-circle": LucideCircleCheckBig,
    "triangle-alert": LucideTriangleAlert,
    info: LucideInfo,
    "help-circle": LucideCircleQuestionMark,
    eye: LucideEye,
    "eye-off": LucideEyeOff,
    lock: LucideLock,
    calendar: LucideCalendar,
    clock: LucideClock,
    map: LucideMap,
    "map-pin": LucideMapPin,
    phone: LucidePhone,
    mic: LucideMic,
    camera: LucideCamera,
    image: LucideImage,
    play: LucidePlay,
    pause: LucidePause,
    square: LucideSquare,
    file: LucideFile,
    folder: LucideFolder,
    send: LucideSend,
    link: LucideLink,
    wifi: LucideWifi,
    bluetooth: LucideBluetooth,
    "battery-full": LucideBatteryFull,
    sun: LucideSun,
    moon: LucideMoon,
    cloud: LucideCloud,
    umbrella: LucideUmbrella,
    sparkles: LucideSparkles,
    flame: LucideFlame,
    zap: LucideZap,
    "arrow-right": LucideArrowRight,
    "arrow-left": LucideArrowLeft,
    "arrow-up": LucideArrowUp,
    "arrow-down": LucideArrowDown,
    "minus-circle": LucideCircleMinus,
    "heart-crack": LucideHeartCrack,
    "sun-dim": LucideSunDim,
    volume: LucideVolume,
    "volume-1": LucideVolume1,
    "volume-2": LucideVolume2,
} as const satisfies Record<string, LucideIcon | LucideIconData>;

export type CupBuiltInIconName = keyof typeof LUCIDE_ICONS;

/**
 * Runtime list of every built-in Lucide name. Useful for building dynamic
 * `provideCupIcons({ names })` calls (e.g. an icon picker) without hardcoding.
 */
export const LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICONS) as readonly CupBuiltInIconName[];
